[versions]
kotlin = "1.8.22"

[libraries]
gradle-kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
commons-io = "commons-io:commons-io:2.11.0"
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
swagger-core = "io.swagger.core.v3:swagger-core:2.2.15"
swagger-parser = "io.swagger.parser.v3:swagger-parser:2.1.16"
commons-codec = "commons-codec:commons-codec:1.16.0"
semver = "org.semver4j:semver4j:4.3.0"
gradle-node = "com.github.node-gradle:gradle-node-plugin:3.5.0"
jgit = "org.eclipse.jgit:org.eclipse.jgit:6.5.0.202303070854-r"
gradle-openapi-generator = "org.openapitools:openapi-generator-gradle-plugin:6.4.0"
json-schema-validator = "com.networknt:json-schema-validator:1.0.85"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.3"
mockk = "io.mockk:mockk:1.13.5"
jsonschematopojo = "org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:1.2.1"
assertj = "org.assertj:assertj-core:3.23.1"
axion-release = "pl.allegro.tech.build:axion-release-plugin:1.15.3"
testcontainers = "org.testcontainers:testcontainers:1.17.6"
okhttp = "com.squareup.okhttp3:okhttp:4.10.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.4.2" }
axion-release = { id = "pl.allegro.tech.build.axion-release", version = "1.15.3" }
sonarqube = { id = "org.sonarqube", version = "4.0.0.2929" }
