name: CI
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ###############################################
  # Run tests and publish coverage to codecov.io
  ###############################################
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Compile
        run: ./gradlew classes testClasses
        env:
          PACKAGE_USER: ${{ secrets.PACKAGES_PAT_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGES_PAT }}
      - name: Lint
        run: ./gradlew ktlintCheck
      - name: Test
        run: ./gradlew test
      - name: Publish Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./codecov/test/jacocoTestReport.xml
      - name: Publish Snapshot
        if: success() && (github.ref_name == 'master' || github.ref_name == 'ronin-5')
        run: ./gradlew publish
        env:
          PACKAGE_USER: ${{ secrets.PACKAGES_PAT_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGES_PAT }}
