name: CICD
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  ###############################################
  # Run tests and publish coverage to codecov.io
  ###############################################
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Compile
        run: ./gradlew classes testClasses
        env:
          PACKAGE_USER: ${{ secrets.PACKAGES_PAT_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGES_PAT }}
      - name: Lint
        run: ./gradlew ktlintCheck
      - name: Test
        run: ./gradlew test
      - name: Publish Snapshot
        # TODO: once done prototyping, only master should actually push artifacts
        # if: success() && github.ref == 'refs/heads/master'
        run: ./gradlew publish
        env:
          PACKAGE_USER: ${{ secrets.PACKAGES_PAT_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGES_PAT }}
